apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Empty string to match PV with no storageClassName
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeName: {{ .Values.pv.name }}
